name: Build and Deploy web
run-name: Build and deploy
on:
  push:
    branches:
      - main
    tags:
      - v*.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo 'building'
  deploy:
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v2
  
