name: Build and Deploy web
run-name: Build and deploy
on:
  push:
    branches:
      - main
    tags:
      - v*.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo 'building'
  deploy:
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create a new tag 
        id: create_tag
        run: |
          VERSION_PREFIX="v"
          VERSION_MAJOR_MINOR="1.0"
          VERSION_PATCH=$(git tag --list "${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.*" --sort=-version:refname | head -n 1 | grep -oE '[0-9]+$')
          if [ -z "$VERSION_PATCH" ]; then
            VERSION_PATCH=0
          else
            VERSION_PATCH=$((VERSION_PATCH + 1))
          fi
          NEW_TAG="${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.${VERSION_PATCH}"
          echo "Generated new tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
      - name: Push new tag 
        run: |
          git push origin ${{ steps.create_tag.outputs.NEW_TAG }}
          echo "New tag pushed"
      - name: Deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v2
  
